# Generated by Django 3.0.3 on 2020-08-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetail',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
