# Generated by Django 3.0.3 on 2020-08-09 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shopdetail_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shop', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='app.ShopDetail')),
            ],
        ),
    ]
