# Generated by Django 3.0.4 on 2020-08-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200809_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/leoontop.JPG', null=True, upload_to='images/'),
        ),
    ]
