# Generated by Django 3.0.4 on 2020-08-10 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shopdetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ShopDetail'),
        ),
    ]
