# Generated by Django 3.0.4 on 2020-08-10 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_product_shopdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shopdetail',
            new_name='shopname',
        ),
    ]
