# Generated by Django 3.0.4 on 2020-08-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200810_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shopname',
            field=models.CharField(default='NOT', max_length=200, null=True),
        ),
    ]
