# Generated by Django 3.0.4 on 2020-08-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200810_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='Description:NA', max_length=200, null=True),
        ),
    ]
